chromeNode:
  enabled: false

firefoxNode:
  enabled: false

edgeNode:
  enabled: true
  replicas: 1
  resources:
    limits:
      cpu: "500m"
      memory: "512Mi"
    requests:
      cpu: "250m"
      memory: "256Mi"

# Opcional: Limita recursos del hub/grid si lo deseas
hub:
  resources:
    limits:
      cpu: "250m"
      memory: "256Mi"
    requests:
      cpu: "100m"
      memory: "128Mi"