apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: selenium-argocd
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/nexusadobo/selenium-gitops
    path: charts/selenium-grid
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: selenium
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true