apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: selenium-hub-manifests
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/nexusadobo/selenium-gitops
    path: manifests
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: selenium
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
