apiVersion: v1
kind: Service
metadata:
  name: selenium-hub
  labels:
    app: selenium-hub
spec:
  type: NodePort   # antes: ClusterIP
  ports:
    - port: 4444
      targetPort: 4444
      nodePort: 30444  # puerto explícito, opcional
      protocol: TCP
  selector:
    app: selenium-hub
