apiVersion: v1
kind: Service
metadata:
  name: selenium-hub-external
  labels:
    app: selenium-hub
spec:
  type: NodePort
  ports:
    - port: 4444
      targetPort: 4444
      nodePort: 30444
      protocol: TCP
  selector:
    app: selenium-hub
