apiVersion: v1
kind: Service
metadata:
  name: selenium-hub
spec:
  selector:
    app: selenium-hub
  ports:
    - name: bus-publish
      port: 4442
      targetPort: 4442
    - name: bus-subscribe
      port: 4443
      targetPort: 4443
    - name: web
      port: 4444
      targetPort: 4444
      nodePort: 30444
  type: NodePort