# values.yaml
selenium-grid:
  hub:
    serviceType: ClusterIP
    resources:
      requests:
        memory: "300Mi"
        cpu: "0.25"
      limits:
        memory: "1Gi"
        cpu: "1"

  chromeNode:
    enabled: true
    replicas: 1
    resources:
      requests:
        memory: "500Mi"
        cpu: "0.5"
      limits:
        memory: "1Gi"
        cpu: "1"

  firefoxNode:
    enabled: false
    replicas: 1
    resources:
      requests:
        memory: "500Mi"
        cpu: "0.5"
      limits:
        memory: "1Gi"
        cpu: "1"

  edgeNode:
    enabled: false