apiVersion: v1
kind: Service
metadata:
  name: selenium-hub
  labels:
    app: selenium-hub
spec:
  type: ClusterIP
  ports:
    - port: 4444
      targetPort: 4444
      protocol: TCP
  selector:
    app: selenium-hub
