apiVersion: batch/v1
kind: Job
metadata:
  name: test-chrome-job
  labels:
    app: selenium-test
spec:
  backoffLimit: 0
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: selenium-test
          image: umihico/aws-lambda-selenium-python:3.11.6-selenium4.14.0-chrome119.0.6045.105
          command: ["python"]
          args:
            - "-c"
            - |
              from selenium import webdriver
              from selenium.webdriver.common.by import By
              from selenium.webdriver.chrome.options import Options
              import time

              options = Options()
              options.add_argument('--no-sandbox')
              options.add_argument('--disable-dev-shm-usage')
              driver = webdriver.Remote(
                  command_executor="http://selenium-hub:4444/wd/hub",
                  options=options
              )
              driver.get("https://www.google.com")
              assert "Google" in driver.title
              driver.quit()
              print("✅ Prueba completada con éxito.")
